---
- name: ensure Git is installed
  apt:
    name: git
    state: present
    update_cache: yes
  become: yes

- name: clone or pull latest code
  git:
    repo: "{{ code_repository }}"
    dest: "{{ app_dir }}"

# TODO: create and start systemd service
# TODO: install postgres on server
