apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "busybeaver.fullname" . }}--cron--queue-github-summary"
  labels:
    type: post-github-summary
    {{- include "busybeaver.labels" . | nindent 4 }}
spec:
  schedule: "50 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: busybeaver--queue-github-summary-jobs
            image: {{ .Values.image.repository }}:{{ .Values.image.version }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["flask"]
            args:
            - "queue_github_summary_jobs"
            env: {{- include "busybeaver.env_vars" . | indent 12 }}
