apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "busybeaver.fullname" . }}-workers"
  namespace: "{{ include "busybeaver.namespace" . }}"
  labels:
    type: worker-deploy
    {{- include "busybeaver.labels" . | nindent 4 }}
  annotations:
    timestamp: "{{ date "20200907150405" .Release.Time }}"
spec:
  replicas: {{ .Values.app.workerReplicaCount }}
  selector:
    matchLabels:
      type: worker
      {{- include "busybeaver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        type: worker
        {{- include "busybeaver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: webapp-worker
        image: {{ .Values.image.repository }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["worker"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
          {{- include "busybeaver.env_vars" . | indent 10 }}
        readinessProbe:
          exec:
            command:
              - bash
              - ./scripts/check_worker_box.sh
          initialDelaySeconds: 10
          periodSeconds: 10
      serviceAccountName: {{ include "busybeaver.serviceAccountName" . }}
      automountServiceAccountToken: false
