apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "busybeaver.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ include "busybeaver.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "busybeaver.fullname" . }}-web
          servicePort: 80
