apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "busybeaver.fullname" . }}--db-migrate"
  namespace: "{{ include "busybeaver.namespace" . }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 120
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrate
        image: {{ .Values.image.repository }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["flask"]
        args: ["db", "upgrade"]
        env: {{- include "busybeaver.env_vars" . | indent 10 }}
      serviceAccountName: {{ include "busybeaver.serviceAccountName" . }}
      automountServiceAccountToken: false
