apiVersion: v1
kind: Service
metadata:
  name: "{{ include "busybeaver.fullname" . }}-web"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.app.port }}
  selector:
    type: web
    {{- include "busybeaver.selectorLabels" . | nindent 4 }}
