# Default values for busybeaver.

environment: production
namespace: busybeaver-production
serviceAccount: busybeaver-production-sa
secretName: bb-prd-terraform-secrets
workspaceId: T093FC1RC

app:
  port: 5000
  webReplicaCount: 1
  workerReplicaCount: 1

ingress:
  host: app.busybeaverbot.com

queue:
  name: bb-queue-production
  dns: bb-queue-production-redis-master.busybeaver-production.svc.cluster.local
