apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "busybeaver.fullname" . }}--cron--post-upcoming-events"
  labels:
    type: post-upcoming-events
    {{- include "busybeaver.labels" . | nindent 4 }}
spec:
  schedule: "0 14 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: busybeaver--post-upcoming-events
            image: {{ .Values.image.repository }}:{{ .Values.image.version }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["flask"]
            args:
            - "poll_twitter"
            - "--workspace"
            - {{ .Values.workspace.id | quote }}
            - "--channel"
            - "announcements"
            - "--group_name"
            - "_ChiPy_"
            - "--count"
            - "5"
            env: {{- include "busybeaver.env_vars" . | indent 12 }}
