# Default values for busybeaver.

environment: staging
namespace: busybeaver-staging
serviceAccount: busybeaver-staging-sa
secretName: bb-stg-terraform-secrets
workspaceId: TKT910ZU0

app:
  port: 5000
  webReplicaCount: 1
  workerReplicaCount: 1

image:
  repository: alysivji/busy-beaver
  version: 1.4.7
  pullPolicy: Always

ingress:
  host: staging.busybeaverbot.com

queue:
  name: bb-queue-staging
  dns: bb-queue-staging-redis-master.busybeaver-staging.svc.cluster.local
