"""create user table

Revision ID: 0b9495faafc3
Revises: 
Create Date: 2018-12-16 02:17:43.901596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9495faafc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.String(length=300), nullable=False),
    sa.Column('github_id', sa.String(length=300), nullable=True),
    sa.Column('github_username', sa.String(length=300), nullable=True),
    sa.Column('github_state', sa.String(length=36), nullable=True),
    sa.Column('github_access_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), nullable=True),
    sa.Column('slack_id', sa.VARCHAR(length=300), nullable=False),
    sa.Column('github_id', sa.VARCHAR(length=300), nullable=True),
    sa.Column('github_username', sa.VARCHAR(length=300), nullable=True),
    sa.Column('github_state', sa.VARCHAR(length=36), nullable=True),
    sa.Column('github_access_token', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
