"""make user table

Revision ID: 3f5a7657912d
Revises: 
Create Date: 2018-12-16 03:58:02.045980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5a7657912d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('slack_id', sa.String(length=300), nullable=False),
    sa.Column('github_id', sa.String(length=300), nullable=True),
    sa.Column('github_username', sa.String(length=300), nullable=True),
    sa.Column('github_state', sa.String(length=36), nullable=True),
    sa.Column('github_access_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
