"""add github login column to user table

Revision ID: 804029511f4c
Revises: 0c21a605424e
Create Date: 2018-12-16 00:12:33.714918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804029511f4c'
down_revision = '0c21a605424e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_username', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'github_username')
    # ### end Alembic commands ###
