"""create api user table

Revision ID: 312e762dfa85
Revises: 3f5a7657912d
Create Date: 2018-12-16 23:02:26.309850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312e762dfa85'
down_revision = '3f5a7657912d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_user')
    # ### end Alembic commands ###
