"""only allow unique keys in key-value store

Revision ID: 73b592804bfa
Revises: c2aead9ff6d9
Create Date: 2019-03-09 12:12:25.914048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b592804bfa'
down_revision = 'c2aead9ff6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'key_value_store', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'key_value_store', type_='unique')
    # ### end Alembic commands ###
