"""make slack installation cols non-nullable

Revision ID: 9bd99c734716
Revises: 1bc5c9bddd73
Create Date: 2019-06-24 02:33:30.021686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9bd99c734716"
down_revision = "1bc5c9bddd73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_installation",
        "access_token",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "authorizing_user_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "bot_access_token",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "bot_user_id",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "scope",
        existing_type=sa.VARCHAR(length=300),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "workspace_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "workspace_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_installation",
        "workspace_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "workspace_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "scope",
        existing_type=sa.VARCHAR(length=300),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "bot_user_id",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "bot_access_token",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "authorizing_user_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "access_token",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    # ### end Alembic commands ###
