"""create twitter poller task table

Revision ID: b5db0d063898
Revises: 8e309a02eb44
Create Date: 2019-04-01 19:28:36.048202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5db0d063898"
down_revision = "8e309a02eb44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_tweet_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["task.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_tweet_task")
    # ### end Alembic commands ###
