"""revert task table creation

Revision ID: 67b2d33c452e
Revises: eaec612dbc5f
Create Date: 2019-04-01 19:03:55.166780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "67b2d33c452e"
down_revision = "eaec612dbc5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_name", table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column(
            "date_created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "date_modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column("failed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("complete", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="task_pkey"),
    )
    op.create_index("ix_task_name", "task", ["name"], unique=False)
    # ### end Alembic commands ###
