"""create slack installation table

Revision ID: a6df75102d6e
Revises: 383bbb33f257
Create Date: 2019-06-18 23:41:59.496770

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "a6df75102d6e"
down_revision = "383bbb33f257"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_installation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column(
            "access_token",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column("authorizing_user_id", sa.String(length=300), nullable=True),
        sa.Column(
            "bot_access_token",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column(
            "bot_user_id",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
            nullable=True,
        ),
        sa.Column("scope", sa.String(length=300), nullable=True),
        sa.Column("state", sa.String(length=36), nullable=True),
        sa.Column("workspace_id", sa.String(length=20), nullable=True),
        sa.Column("workspace_name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_slack_installation_state"),
        "slack_installation",
        ["state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slack_installation_workspace_id"),
        "slack_installation",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_slack_installation_workspace_id"), table_name="slack_installation"
    )
    op.drop_index(op.f("ix_slack_installation_state"), table_name="slack_installation")
    op.drop_table("slack_installation")
    # ### end Alembic commands ###
