"""one-to-many between slack instalation and github summary users

Revision ID: 1bc5c9bddd73
Revises: dee7af02d018
Create Date: 2019-06-23 15:52:51.199373

"""
from alembic import op
import sqlalchemy as sa

from busy_beaver.config import IN_PRODUCTION


# revision identifiers, used by Alembic.
revision = "1bc5c9bddd73"
down_revision = "dee7af02d018"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Schema migration
    # Add column to store installation_id
    op.add_column(
        "github_summary_user", sa.Column("installation_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_installation_id",
        "github_summary_user",
        "slack_installation",
        ["installation_id"],
        ["id"],
    )

    # Step 2: Data migration
    # Set all github_user data to correct installation_id
    if IN_PRODUCTION:
        engine = op.get_bind()
        meta = sa.MetaData(bind=engine)
        slack_installation = sa.Table("slack_installation", meta, autoload=True)
        github_summary_user = sa.Table("github_summary_user", meta, autoload=True)

        # ChiPy was first workspace; migrate all users
        stmt = sa.select([slack_installation.c.id]).where(
            slack_installation.c.workspace_id == "T093FC1RC"
        )
        result = engine.execute(stmt).fetchone()
        slack_installation_id = result[0]

        stmt = github_summary_user.update().values(
            installation_id=slack_installation_id
        )
        engine.execute(stmt)

    # Step 3: Schema migration
    # Ensure installation_id foreign_key cannot be empty
    op.alter_column("github_summary_user", "installation_id", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_installation_id", "github_summary_user", type_="foreignkey")
    op.drop_column("github_summary_user", "installation_id")
    # ### end Alembic commands ###
