"""create github task table

Revision ID: 68b0d9af5775
Revises: db7c0ad04da5
Create Date: 2019-03-30 19:09:47.140066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68b0d9af5775"
down_revision = "db7c0ad04da5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_github_summary_task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["task.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_github_summary_task")
    # ### end Alembic commands ###
