"""remove state column and make other columns required

Revision ID: 05fd1af68aa4
Revises: a6df75102d6e
Create Date: 2019-06-22 04:53:46.341696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "05fd1af68aa4"
down_revision = "a6df75102d6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_slack_installation_state", table_name="slack_installation")
    op.drop_column("slack_installation", "state")

    op.alter_column(
        "slack_installation",
        "access_token",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "authorizing_user_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "bot_access_token",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "bot_user_id",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "scope",
        existing_type=sa.VARCHAR(length=300),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "workspace_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "slack_installation",
        "workspace_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_installation",
        "workspace_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "workspace_id",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "scope",
        existing_type=sa.VARCHAR(length=300),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "bot_user_id",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "bot_access_token",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "authorizing_user_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=True,
    )
    op.alter_column(
        "slack_installation",
        "access_token",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )

    op.add_column(
        "slack_installation",
        sa.Column("state", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_slack_installation_state", "slack_installation", ["state"], unique=False
    )
    # ### end Alembic commands ###
