"""add user and type columns to task table

Revision ID: db7c0ad04da5
Revises: eaec612dbc5f
Create Date: 2019-03-30 17:49:12.126475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db7c0ad04da5"
down_revision = "eaec612dbc5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("type", sa.String(length=55), nullable=True))
    op.add_column("task", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_task_user_id", "task", "api_user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_task_user_id", "task", type_="foreignkey")
    op.drop_column("task", "user_id")
    op.drop_column("task", "type")
    # ### end Alembic commands ###
