"""add roll to api user

Revision ID: 05a6d5f7eeac
Revises: 78514b173380
Create Date: 2019-02-07 03:20:46.494056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a6d5f7eeac'
down_revision = '78514b173380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user', sa.Column('role', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_user', 'role')
    # ### end Alembic commands ###
