"""add roles to api user

Revision ID: c2aead9ff6d9
Revises: 500e1baf1bef
Create Date: 2019-03-03 14:10:03.776587

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c2aead9ff6d9"
down_revision = "500e1baf1bef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_user",
        sa.Column("role", sa.String(length=255), nullable=False, server_default="user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_user", "role")
    # ### end Alembic commands ###
