"""create task tables: general + post github summary

Revision ID: 8e309a02eb44
Revises: 67b2d33c452e
Create Date: 2019-04-01 19:06:01.602553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e309a02eb44"
down_revision = "67b2d33c452e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("failed", sa.Boolean(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=55), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["api_user.id"], name="fk_task_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_job_id"), "task", ["job_id"], unique=False)
    op.create_index(op.f("ix_task_name"), "task", ["name"], unique=False)
    op.create_table(
        "post_github_summary_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["task.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_github_summary_task")
    op.drop_index(op.f("ix_task_name"), table_name="task")
    op.drop_index(op.f("ix_task_job_id"), table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###
