"""remove unused task tables

Revision ID: 9151e4b0a560
Revises: 14181eb1a202
Create Date: 2020-04-19 05:21:07.102875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9151e4b0a560"
down_revision = "14181eb1a202"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Drop tables
    op.drop_table("sync_event_database_task")
    op.drop_table("post_github_summary_task")
    op.drop_table("post_tweet_task")

    # Step 2: Truncate task table
    engine = op.get_bind()
    meta = sa.MetaData(bind=engine)
    task = sa.Table("task", meta, autoload=True)
    engine.execute(task.delete())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_tweet_task",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["id"], ["task.id"], name="post_tweet_task_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="post_tweet_task_pkey"),
    )
    op.create_table(
        "post_github_summary_task",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["task.id"], name="post_github_summary_task_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="post_github_summary_task_pkey"),
    )
    op.create_table(
        "sync_event_database_task",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["task.id"], name="fetch_new_events_task_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="fetch_new_events_task_pkey"),
    )
    # ### end Alembic commands ###
