"""add enabled field to github_summary_config

Revision ID: f1adfb5b4d39
Revises: 9bc99f240f5f
Create Date: 2020-07-11 14:59:22.112438

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f1adfb5b4d39"
down_revision = "9bc99f240f5f"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Schema migration
    # Add enabled field that is nullable
    op.add_column(
        "github_summary_configuration",
        sa.Column("enabled", sa.Boolean(), nullable=True),
    )

    # Step 2: Data migration
    # Set enabled=False
    engine = op.get_bind()
    meta = sa.MetaData(bind=engine)
    event = sa.Table("github_summary_configuration", meta, autoload=True)
    stmt = event.update().values(enabled=False)
    engine.execute(stmt)

    # Step 3: Data migration
    # enabled field cannot be nullable
    op.alter_column("github_summary_configuration", "enabled", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_summary_configuration", "enabled")
    # ### end Alembic commands ###
