"""add app_home_opened_count to slack_user

Revision ID: 44515a4bff4d
Revises: eddd9fbf0db6
Create Date: 2020-07-05 23:23:00.963727

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "44515a4bff4d"
down_revision = "eddd9fbf0db6"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1 -- Add nullable column
    op.add_column(
        "slack_user", sa.Column("app_home_opened_count", sa.Integer(), nullable=True)
    )

    # Step 2 -- Fill in column with default values
    op.execute("UPDATE slack_user SET app_home_opened_count = 0")

    # Step 3 -- Set column to be non-nullable
    op.alter_column("slack_user", "app_home_opened_count", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_user", "app_home_opened_count")
    # ### end Alembic commands ###
