"""relate github summary config to github users

Revision ID: 8906cc54f4cd
Revises: 6d128f97bf34
Create Date: 2020-04-19 00:53:53.206962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from busy_beaver.models import GitHubSummaryUser

# revision identifiers, used by Alembic.
revision = "8906cc54f4cd"
down_revision = "6d128f97bf34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_summary_user", sa.Column("config_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_github_summary_configuration_id",
        "github_summary_user",
        "github_summary_configuration",
        ["config_id"],
        ["id"],
    )
    # ### end Alembic commands ###

    session = Session(bind=op.get_bind())

    users = session.query(GitHubSummaryUser).all()
    for user in users:
        user.configuration = user.installation.github_summary_config
        session.add(user)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_github_summary_configuration_id", "github_summary_user", type_="foreignkey"
    )
    op.drop_column("github_summary_user", "config_id")
    # ### end Alembic commands ###
