"""modify task model for new use case

Revision ID: 6ca59a92db5c
Revises: 337517ec92c5
Create Date: 2020-07-08 13:24:43.771585

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6ca59a92db5c"
down_revision = "337517ec92c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "complete")
    op.drop_column("task", "description")
    op.drop_column("task", "failed")
    op.drop_column("task", "type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("type", sa.VARCHAR(length=55), autoincrement=False, nullable=True),
    )
    op.add_column(
        "task", sa.Column("failed", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "task",
        sa.Column(
            "description", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "task", sa.Column("complete", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
