"""add post_cron_enabled field

Revision ID: 9e34ca8cefc0
Revises: caf810949fa5
Create Date: 2020-08-13 18:47:41.965149

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9e34ca8cefc0"
down_revision = "caf810949fa5"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Schema migration
    op.add_column(
        "upcoming_events_configuration",
        sa.Column("post_cron_enabled", sa.Boolean(), nullable=True),
    )

    # Step 2: Data migration
    engine = op.get_bind()
    meta = sa.MetaData(bind=engine)
    upcoming_events_configuration = sa.Table(
        "upcoming_events_configuration", meta, autoload=True
    )
    stmt = upcoming_events_configuration.update().values(post_cron_enabled=False)
    engine.execute(stmt)

    # Step 3: Schema migration
    op.alter_column(
        "upcoming_events_configuration", "post_cron_enabled", nullable=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upcoming_events_configuration", "post_cron_enabled")
    # ### end Alembic commands ###
