"""add slack_user table

Revision ID: eddd9fbf0db6
Revises: 9151e4b0a560
Create Date: 2020-07-05 16:09:04.051330

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "eddd9fbf0db6"
down_revision = "9151e4b0a560"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.Column("slack_id", sa.String(length=30), nullable=False),
        sa.Column("slack_oauth_state", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["slack_installation.id"], name="fk_installation_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_slack_user_installation_id"),
        "slack_user",
        ["installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slack_user_slack_id"), "slack_user", ["slack_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slack_user_slack_id"), table_name="slack_user")
    op.drop_index(op.f("ix_slack_user_installation_id"), table_name="slack_user")
    op.drop_table("slack_user")
    # ### end Alembic commands ###
