"""add workspace logo url field

Revision ID: 102c4e5f4066
Revises: c9971d11c82f
Create Date: 2020-07-29 00:15:35.565444

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "102c4e5f4066"
down_revision = "c9971d11c82f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_installation",
        sa.Column(
            "workspace_logo_url", sqlalchemy_utils.types.url.URLType(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_installation", "workspace_logo_url")
    # ### end Alembic commands ###
