"""remove token auth table

Revision ID: 14181eb1a202
Revises: 8906cc54f4cd
Create Date: 2020-04-19 04:49:50.421722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14181eb1a202"
down_revision = "8906cc54f4cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_task_user_id", "task", type_="foreignkey")
    op.drop_column("task", "user_id")

    op.drop_table("api_user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "date_created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "date_modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            sa.VARCHAR(length=255),
            server_default=sa.text("'user'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="api_user_pkey"),
    )

    op.add_column(
        "task", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("fk_task_user_id", "task", "api_user", ["user_id"], ["id"])
    # ### end Alembic commands ###
