"""create call_for_proposals_onfig table

Revision ID: e51108c88034
Revises: abcab0310efc
Create Date: 2020-09-25 14:59:25.268465

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e51108c88034"
down_revision = "abcab0310efc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_for_proposals_configuration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("internal_cfps", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["slack_installation.id"], name="fk_installation_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call_for_proposals_configuration")
    # ### end Alembic commands ###
