"""add meetup groups middle layer between events

Revision ID: f29c0fd74c68
Revises: 67025a818f50
Create Date: 2020-07-12 16:16:34.770629

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f29c0fd74c68"
down_revision = "67025a818f50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upcoming_events_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("meetup_urlname", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["upcoming_events_configuration.id"],
            name="fk_upcoming_events_configuration_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("event", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_upcoming_events_group_id",
        "event",
        "upcoming_events_group",
        ["group_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_upcoming_events_group_id", "event", type_="foreignkey")
    op.drop_column("event", "group_id")
    op.drop_table("upcoming_events_group")
    # ### end Alembic commands ###
