"""remove slack_oauth_state column

Revision ID: 3f137bef24e4
Revises: 21e8f6f7a837
Create Date: 2020-07-06 04:20:47.952399

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3f137bef24e4"
down_revision = "21e8f6f7a837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_user", "slack_oauth_state")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_user",
        sa.Column(
            "slack_oauth_state",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
