"""make channel field nullable

Revision ID: 636be46da1fe
Revises: 9e34ca8cefc0
Create Date: 2020-09-17 20:10:08.370810

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "636be46da1fe"
down_revision = "9e34ca8cefc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "upcoming_events_configuration",
        "channel",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "upcoming_events_configuration",
        "channel",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    # ### end Alembic commands ###
