"""add installation to kv table

Revision ID: 6d128f97bf34
Revises: 4355643c48c3
Create Date: 2020-04-12 16:17:17.088867

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6d128f97bf34"
down_revision = "4355643c48c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "key_value_store", sa.Column("installation_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_installation_id",
        "key_value_store",
        "slack_installation",
        ["installation_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_installation_id", "key_value_store", type_="foreignkey")
    op.drop_column("key_value_store", "installation_id")
    # ### end Alembic commands ###
