"""create upcoming events config table

Revision ID: 67025a818f50
Revises: f1adfb5b4d39
Create Date: 2020-07-12 15:43:40.023276

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "67025a818f50"
down_revision = "f1adfb5b4d39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upcoming_events_configuration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["slack_installation.id"], name="fk_installation_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upcoming_events_configuration")
    # ### end Alembic commands ###
