"""create_slack_app_home_opened_counter

Revision ID: d82107e59a16
Revises: 8c5ac2860989
Create Date: 2020-01-24 15:34:32.181767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d82107e59a16"
down_revision = "8c5ac2860989"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_app_home_opened",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.Column("slack_id", sa.String(length=30), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["slack_installation.id"], name="fk_installation_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slack_app_home_opened")
    # ### end Alembic commands ###
