"""update task table

Revision ID: 7f913400224c
Revises: 337517ec92c5
Create Date: 2020-07-08 00:54:13.270220

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7f913400224c"
down_revision = "337517ec92c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("data", sa.JSON(), nullable=True))
    op.add_column("task", sa.Column("state", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_task_state"), "task", ["state"], unique=False)
    op.create_index(op.f("ix_task_type"), "task", ["type"], unique=False)
    op.drop_column("task", "failed")
    op.drop_column("task", "description")
    op.drop_column("task", "complete")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("complete", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "task",
        sa.Column(
            "description", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "task", sa.Column("failed", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_task_type"), table_name="task")
    op.drop_index(op.f("ix_task_state"), table_name="task")
    op.drop_column("task", "state")
    op.drop_column("task", "data")
    # ### end Alembic commands ###
