"""add_cascade_delete

Revision ID: c9971d11c82f
Revises: 31f9b92e97db
Create Date: 2020-07-27 23:16:15.227491

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9971d11c82f"
down_revision = "31f9b92e97db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_upcoming_events_group_id", "event", type_="foreignkey")
    op.create_foreign_key(
        "fk_upcoming_events_group_id",
        "event",
        "upcoming_events_group",
        ["group_id"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_upcoming_events_group_id", "event", type_="foreignkey")
    op.create_foreign_key(
        "fk_upcoming_events_group_id",
        "event",
        "upcoming_events_group",
        ["group_id"],
        ["id"],
    )
    # ### end Alembic commands ###
