"""add installation to kv table

Revision ID: 6d128f97bf34
Revises: 4355643c48c3
Create Date: 2020-04-12 16:17:17.088867

"""
from alembic import op
import sqlalchemy as sa

from busy_beaver.config import IN_PRODUCTION

# revision identifiers, used by Alembic.
revision = "6d128f97bf34"
down_revision = "4355643c48c3"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Schema migration
    # Add column to store installation_id
    op.add_column(
        "key_value_store", sa.Column("installation_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_installation_id",
        "key_value_store",
        "slack_installation",
        ["installation_id"],
        ["id"],
    )

    # Step 2: Data migration
    # Set all github_user data to correct installation_id
    if IN_PRODUCTION:
        engine = op.get_bind()
        meta = sa.MetaData(bind=engine)
        slack_installation = sa.Table("slack_installation", meta, autoload=True)
        key_value_store = sa.Table("key_value_store", meta, autoload=True)

        # ChiPy was first workspace; migrate all users
        stmt = sa.select([slack_installation.c.id]).where(
            slack_installation.c.workspace_id == "T093FC1RC"
        )
        result = engine.execute(stmt).fetchone()
        slack_installation_id = result[0]

        stmt = key_value_store.update().values(installation_id=slack_installation_id)
        engine.execute(stmt)

    # Step 3: Schema migration
    # Ensure installation_id foreign_key cannot be empty
    op.alter_column("key_value_store", "installation_id", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_installation_id", "key_value_store", type_="foreignkey")
    op.drop_column("key_value_store", "installation_id")
    # ### end Alembic commands ###
