"""add fields for time and timezone

Revision ID: a97292c2b635
Revises: 3f137bef24e4
Create Date: 2020-07-06 19:19:01.413325

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "a97292c2b635"
down_revision = "3f137bef24e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_summary_configuration",
        sa.Column("summary_post_time", sa.Time(), nullable=True),
    )
    op.add_column(
        "github_summary_configuration",
        sa.Column(
            "summary_post_timezone",
            sqlalchemy_utils.types.timezone.TimezoneType(backend="pytz"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_summary_configuration", "summary_post_timezone")
    op.drop_column("github_summary_configuration", "summary_post_time")
    # ### end Alembic commands ###
