"""remove user token column

Revision ID: 1fe0aa535040
Revises: e51108c88034
Create Date: 2020-10-01 18:36:02.685882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1fe0aa535040"
down_revision = "e51108c88034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_installation", "access_token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_installation",
        sa.Column(
            "access_token", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
