"""remove slack installation state

Revision ID: 7959c628791e
Revises: 68ff4349ae47
Create Date: 2020-07-26 15:26:34.040967

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7959c628791e"
down_revision = "68ff4349ae47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_installation", "state")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_installation",
        sa.Column("state", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
