"""add time_to_post column

Revision ID: 12a693d95f87
Revises: 102c4e5f4066
Create Date: 2020-07-29 02:10:07.847585

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "12a693d95f87"
down_revision = "102c4e5f4066"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("time_to_post", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "time_to_post")
    # ### end Alembic commands ###
