"""add organization name field

Revision ID: caf810949fa5
Revises: 12a693d95f87
Create Date: 2020-08-13 18:09:49.751741

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "caf810949fa5"
down_revision = "12a693d95f87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_installation",
        sa.Column("organization_name", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_installation", "organization_name")
    # ### end Alembic commands ###
