"""remove redundant columns

Revision ID: 337517ec92c5
Revises: a97292c2b635
Create Date: 2020-07-07 02:57:28.121225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "337517ec92c5"
down_revision = "a97292c2b635"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_summary_configuration", "timezone_info")
    op.drop_column("github_summary_configuration", "time_to_post")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_summary_configuration",
        sa.Column(
            "time_to_post", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "github_summary_configuration",
        sa.Column(
            "timezone_info",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
