name: release
on: [pull_request]
jobs:
  test-app-build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull image
        run: docker pull alysivji/busy-beaver:latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: alysivji/busy-beaver
          always_pull: true
          dockerfile: docker/prod/Dockerfile
          tags: test-tag
