name: release
on: [pull_request]
jobs:
  test-app-build-and-push-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: alysivji/busy-beaver
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Pull latest image
        run: docker pull ${{ env.IMAGE_NAME }} || true
      - name: Build and push Docker image
        run: docker build -f docker/prod/Dockerfile --pull --cache-from ${{ env.IMAGE_NAME }} --tag ${{ env.IMAGE_NAME }} --tag ${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA }} .
      - name: Push images
        run: |
          docker push ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA }}
