name: release
on: [pull_request]
jobs:
  test-app-build-and-push-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: alysivji/busy-beaver
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v2
      - name: Login to DockerHub
        run: echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - name: Pull latest image
        run: docker pull $IMAGE_NAME || true
      - name: Build and push Docker image
        run: docker build -f docker/prod/Dockerfile --pull --cache-from $IMAGE_NAME --tag $IMAGE_NAME --tag $IMAGE_NAME:$GITHUB_SHA .
      - name: Push images
        run: |
          docker push $IMAGE_NAME
          docker push $IMAGE_NAME:$GITHUB_SHA
