name: release
on: [pull_request]
jobs:
  test-app-build-and-push-image:
    runs-on: ubuntu-latest

    container: python:3.8.1-buster
    env:
      PYTHONPATH: .
      FLASK_APP: /app/busy_beaver/__init__.py
      FLASK_ENV: development
      DATABASE_URI: postgresql://bbdev_user:bbdev_password@db:5432/busy-beaver
      REDIS_URI: redis://redis:6379
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: alysivji/busy-beaver
          always_pull: true
          dockerfile: docker/prod/Dockerfile
          tags: $GITHUB_SHA
