# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.8.1-buster
    env:
      PYTHONPATH: .
      FLASK_APP: /app/busy_beaver/__init__.py
      FLASK_ENV: development
      DATABASE_URI: postgresql://bbdev_user:bbdev_password@db:5432/busy-beaver
      REDIS_URI: redis://redis:6379
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: make up
    - name: Test application
      run: make test
