# Default values for busybeaver.

environment: staging
secretName: busybeaver-staging
workspaceId: TKT910ZU0

app:
  port: 5000
  webReplicaCount: 1
  workerReplicaCount: 1

image:
  repository: alysivji/bb-test
  version: "1.0"
  pullPolicy: Always

ingress:
  host: staging.busybeaverbot.com
