# Default values for busybeaver.

environment: staging

app:
  port: 5000
  webReplicaCount: 1
  workerReplicaCount: 1

image:
  repository: alysivji/busy-beaver
  version: 1.4.1
  pullPolicy: Always

ingress:
  host: staging.busybeaverbot.com
